<?php

namespace Zcomdezign\PlatformBundle\Repository;

/**
 * ArticlePictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlePictureRepository extends \Doctrine\ORM\EntityRepository
{
}